---
# file: roles/roborio/tasks/toolchain.yml

- include_vars: toolchain.yml

- name: configure FRC toolchain PPA
  apt_repository:
    repo: "{{ toolchain.ppa }}"
    state: present
  register: toolchain_ppa_state
  tags: frc

- name: update apt cache
  apt:
    update_cache: yes
  when: toolchain_ppa_state.changed

- name: install FRC toolchain
  apt:
    name: "{{ toolchain.deb }}"
    state: latest
    update_cache: no
  tags: tools, frc
