---
# file: roles/pyfrc/tasks/main.yml

- name: install python packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pyfrc.python }}"
  tags: pyfrc

- name: install python pips
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items: "{{ pyfrc.pips }}"
  tags: pyfrc
