---
# file: roles/bazel/tasks/main.yml

- name: configure JDK 8 PPA
  apt_repository:
    repo: "{{ java.ppa }}"
    state: present
  register: java_ppa_state


- name: accept Oracle JDK license
  shell: echo debconf {{ java.license }} select true | sudo debconf-set-selections
  changed_when: false

- name: configure Bazel distribution as package source
  apt_repository:
    repo: "{{ bazel.source }}"
    filename: bazel
    state: present
  register: bazel_ppa_state

- name: add Bazel public key
  apt_key: url={{ bazel.key }} state=present
  tags: frc

- name: update apt cache
  apt:
    update_cache: yes
  when: java_ppa_state.changed or bazel_ppa_state.changed

- name: install JDK 8
  apt:
    name: "{{ java.deb }}"
    state: latest
    update_cache: no

- name: install Bazel
  apt:
    name: "{{ bazel.deb }}"
    state: latest
    update_cache: no
