---
# file: roles/opencv/tasks/opencv.yml

- name: install cmake
  apt:
    name: cmake
    state: latest
  tags: opencv

- name: install opencv
  apt:
    name: libopencv-dev
    state: latest
  tags: opencv
