---
# file: roles/cmake/tasks/main.yml

- name: configure cmake 3 PPA
  apt_repository:
    repo: "{{ ppa }}"
    state: present
  register: cmake_ppa_state
  tags: cmake

- name: update apt cache
  apt:
    update_cache: yes
  when: cmake_ppa_state.changed
  tags: cmake

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: no
  with_items: "{{ debs }}"
  tags: cmake
