---
# file: roles/opencv/vars/opencv.yml

opencv:
  src_dir: /usr/local/src/opencv
  debs:
    - libjpeg-dev
    - libtiff5-dev
    - libjasper-dev
    - libpng12-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-dev
    - libxvidcore-dev
    - libx264-dev
    - libtbb2
    - libtbb-dev
    - libdc1394-22-dev
    - libgtk-3-dev
    - libatlas-base-dev
    - libgphoto2-dev
    - git
    - build-essential
    - cmake
    - pkg-config
    - doxygen
    - gfortran
    - cheese
    - uvcdynctrl
  repo: http://github.com/opencv/opencv
  version: 2.4
  nvidia:
    - nvidia-cuda-dev
    - nvidia-cuda-doc
    - nvidia-cuda-gdb
    - nvidia-cuda-toolkit
    - nvidia-opencl-dev
    - nvidia-opencl-icd-361
    - nvidia-profiler
    - nvidia-visual-profiler
