---
# This playbook contains common plays for all nodes.

- name: set hostname
  hostname: name={{inventory_hostname}}
  when: ansible_virtualization_role != "guest"
  tags: sf

- name: fix stdin: is not a tty warning
  lineinfile:
    dest: /root/.profile
    regexp: '^mesg n'
    line: tty -s && mesg n
    state: present

- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400
  tags: sf

- name: install Avahi service
  apt: name=avahi-daemon state=latest
  tags: sf

- name: start Avahi service
  service: enabled=yes state=started name="avahi-daemon"
  tags: sf

- name: install ntp
  apt: name=ntp state=latest
  when: ansible_virtualization_role != "guest"
  tags: ntp

- name: start the ntp service
  service: name=ntp state=started enabled=yes
  when: ansible_virtualization_role != "guest"
  tags: ntp

- name: install extra packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common.extras }}"
  tags: sf

- name: update all packages
  apt: upgrade=dist

- name: display all variables/facts known for a host
  debug: var=hostvars[inventory_hostname] verbosity=4
