---
# file: roles/workstation/vars/main.yml

atom:
  target_version: "Version: 1.9.7"
  deb: https://github.com/atom/atom/releases/download/v1.9.7/atom-amd64.deb

libisl13:
  target_version: "Version: 0.14-1"
  deb: http://launchpadlibrarian.net/191842424/libisl13_0.14-1_amd64.deb

workstation:
  libs:
    - libjpeg-dev
    - libtiff5-dev
    - libjasper-dev
    - libpng12-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-dev
    - libxvidcore-dev
    - libx264-dev
    - libtbb2
    - libtbb-dev
    - libdc1394-22-dev
    - libgtk-3-dev
    - libatlas-base-dev
    - libgphoto2-dev
  python:
    - python3-pip
    - python2.7-dev
    - python3-dev
    - python3-numpy
    - python3-virtualenv
    - virtualenvwrapper
    - python3-matplotlib
  tools:
    - git
    - build-essential
    - cmake
    - pkg-config
    - doxygen
    - gfortran
    - clang
    - clang-format
    - clang-tidy
    - lldb
    - ruby
    - vim
    - frc-toolchain
  cuda:
    - nvidia-cuda-dev
    - nvidia-cuda-toolkit
  gems:
    - gist
