# roles/roborio/vars/navx.yml
---
navx_zip: navx-mxp-libs.zip
navx_version: 3.0.327
navx_url: http://www.kauailabs.com/public_files/navx-mxp/{{ navx_zip }}
navx_sha256: d62a7ed2ab23310ca2f4ab6236439ff17ec88a155ee862bf2e3bcaa665377f39
